version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: pet-care-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_care
      MYSQL_USER: app_user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
